addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chef

branches:
  only:
  - master

before_script:
  - export PATH="/opt/chef/bin:$PATH"

language: ruby
sudo: false
rvm:
  - 2.2
  - 2.1
