addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chef

branches:
  only:
  - master

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

script: bundle exec rake spec

language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.4.1
    - rvm: 2.3.3
    - rvm: 2.4.1
      env:
        CHEFSTYLE: 1
      script: bundle exec rake style
